export default {
  name: "job",
  title: "Job",
  type: "document",
  fields: [
    {
      name: "title",
      title: "Title",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "org",
      title: "Org",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "vacancy_page",
      title: "Vacancy Page",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "location",
      title: "Location",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "date_published",
      title: "Date Published",
      type: "date",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "date_it_closes",
      title: "Date It Closes",
      type: "date",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "problem_area_main",
      title: "Problem Area Main",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "problem_area_others",
      title: "Problem Area Others",
      type: "string",
    },
    {
      name: "description",
      title: "Description",
      type: "array",
      of: [{ type: "block" }],
      validation: (Rule) => Rule.required(),
    },
    {
      name: "required_degree",
      title: "Required Degree",
      type: "reference",
      to: [{ type: "qualification" }],
      validation: (Rule) => Rule.required(),
    },
    {
      name: "required_experience",
      title: "Required Experience",
      type: "reference",
      to: [{ type: "experience" }],
      validation: (Rule) => Rule.required(),
    },
    {
      name: "role_type",
      title: "Role Type",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "orgs_home_page",
      title: "Orgs Home Page",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "orgs_vacancies_page",
      title: "Orgs Vacancies Page",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "orgs_logo",
      title: "Orgs Logo",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    // Added fields:
    {
      name: "countries",
      title: "Locations",
      type: "array",
      of: [{ type: "reference", to: [{ type: "location" }] }],
      validation: (Rule) => Rule.required(),
    },
    {
      name: "problem_areas",
      title: "Problem Areas",
      type: "array",
      of: [{ type: "reference", to: [{ type: "area" }] }],
      validation: (Rule) => Rule.required(),
    },
    {
      name: "roles",
      title: "Roles",
      type: "array",
      of: [{ type: "reference", to: [{ type: "role" }] }],
      validation: (Rule) => Rule.required(),
    },
  ],
}
